### PR TITLE
added options to limit how deep level of the DOM tree should be diff

### PR DESCRIPTION
**Pull request by unbug**
I've read the whole source codes,my first idea is use linked list instead of array,because DOM tree actually is a doubly linked lists,but it's too tough to get started,not sure if it's the right way to go,I guess I am just not ready for this.
So I tried the DOM level first,it helps a lot when my DOM tree is too large and too deep and it's not worth to diff them all.
I can't find a better way to get rid of the while loop when count the DOM levels,do you have a better idea?
My next step is try to add a selector filter,which maybe more custom-able,because the levels way is too wide range.

### CODE REVIEW

**Comment by unbug** [comment]
I didn't move move them,because in my case I change the levelsDeep in different situations.
Again,  
I can't find a better way to get rid of the while loop when count the DOM levels,do you have a better idea?
My next step is try to add a selector filter,which maybe more custom-able,because the levels way is too wide range,do you have any guide for me?

**Comment by johanneswilm** [comment]
> my first idea is use linked list instead of array

Where were you thinking about using that? For the array of diffs that being output? Remember that one needs to be able to convert whatever structure to JSON to send over networks, so double/triple linking will likely be problematic.

If you were thinking of using a two-step process in which one would first convert the DOM structure to a structure of Javascript objects (linked lists or however), then do the diffing operation on those, then that is also something I have thought about. It may give performance gains. Feel free to experiment with that.

> I didn't move move them,because in my case I change the levelsDeep in different situations.

Ok, but is there anything preventing you from using different instances of diffDOM?

**Comment by unbug** [comment]
I've pack the diffDOM in a factory,the render part is not in my VIEW,so it's better to be "singleton".

**Comment by unbug** [comment]
I think the  selector filter is even more better and fast,but I don't know where to stop the loop when the diff is looking into the whole DOM tree.

**Comment by johanneswilm** [comment]
> I've pack the diffDOM in a factory,the render part is not in my VIEW,so it's better to be "singleton".

Ok, but given that this is a generic library, I think you will need to move it there, even if it means a few more lines of code on your end. It would be difficult/impossible for others to understand why some options are in one place and other options in other places. So consistency is important.

> but I don't know where to stop the loop when the diff is looking into the whole DOM tree.

You will need to record the node that the diff is executed on by the user, and then check if you are X levels away from that. You can either do that by going from the node to its parents nodes and see how many levels you will have to go through, or maybe it is even quicker to add some logic that records how many times it goes through the findInnerDiff to reach the current level, and that should also give you the level of depth.

**Comment by johanneswilm** [comment]
@unbug : Maybe it would be simpler to simply convert to a "virtual dom" first and then do all the diffing there? It would require two types of apply mechanisms: one for the virtual dom and one for the real one. The main problem with trying that seems to be that it is unknown if and how much of a gain it would give before one actually tries it out. But all the logic should be the same.

**Comment by unbug** [comment]
@johanneswilm the virtual dom idea is great,but in many case,we update the real DOM by use other script,in this case,we have to sync it to our virtual dom.

**Comment by unbug** [comment]
What's the best way to auto apply the diff?So we can get rid of the extra  nest loop for the apply method.Or is this a good idea?Because if we update the DOM will slow down our diff finder.

**Comment by johanneswilm** [comment]
> the virtual dom idea is great,but in many case,we update the real DOM by use other script,in this case,we have to sync it to our virtual dom.

This would be entirely inside of the diffing mechanism. So if you ask for diff between node A and B it would:

1. Create a virtual version of A
2. Create a virtual version of B
3. Create a diff between virtual A and virtual B.
4. Return diff

So the virtual dom elements would only be inside the diffing mechanism and hopefully lead to a major speed-up especially for large projects, such as yours.

 > What's the best way to auto apply the diff?So we can get rid of the extra nest loop for the apply method.Or is this a good idea?Because if we update the DOM will slow down our diff finder.

Just comment out lines 537/538:
```
    t1 = cleanCloneNode(t1);
    t2 = cleanCloneNode(t2);
```

I tried that a few days ago. Unfortunately the speedup of that is around 0.003 seconds when the full diffing operation takes 27 seconds. So I decided it wasn't worth it.

**Comment by unbug** [comment]
About the virtual DOM idea,here is my flow:
1. convent html to virtual-dom,by [html-to-vdom](https://github.com/TimBeyer/html-to-vdom)
2. diff them,by [this](https://github.com/Matt-Esch/virtual-dom/blob/master/vtree/README.md)
3. apply the diff patch,by [this](https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/README.md)

**Comment by johanneswilm** [comment]
@unbug: ok, so this all exists already? What do you need diffDOM for?

**Comment by unbug** [comment]
diffDOM is lite.That's the good part,I'm still digging :)

**Comment by unbug** [comment]
I still don't get why virtual dom is fast?it's use the document.createElement too,diffDOM use cloneNode,it's the same,right?

**Comment by johanneswilm** [comment]
@unbug : I have made a test in the vdom branch [1]. And it is just a lot faster not to use that. Most tests work, but there are still a few bugs which have to be squashed. But I already noticed it makes it go about 4 times faster on your site with npo performance parameters enabled. Maybe it would make sense for you to build on that one? Another enhancement could be the route. It starts from 0 every time a diff has been made. Maybe it would make sense to make it skip certain parts of the tree once it has finished a certain part of the tree? That should mean quite a lot of speed up.

[1] https://github.com/fiduswriter/diffDOM/tree/vdom

**Comment by unbug** [comment]
Great work!I just test the vdom branch in my real project,it's a lot fast now,170kb,10 times test,takes 17s a time(MBP 13',2012years,osx 10.11,latest chrome),the browser never crash!Any thing I can help?

**Comment by episodeyang** [comment]
@johanneswilm Just want to chime in because the vdom branch is too interesting to miss.

I read the commit but am still kind of confused about where the speed up came from.

1. do you have to patch both the vdom *and* the html?
2. is the speed up from the patching?

**Comment by johanneswilm** [comment]
> do you have to patch both the vdom and the html?

@episodeyang: No, it uses only the vdom during the creation of the list of diffs and then hands that to the user, who can then patch a normal dom object with it. Before it created a copy of the elements that were to be patched. And that just took longer time. That's why there are two apply functions now. One is just used internally, the other one is just used externally.

> Any thing I can help?

@unbug + @episodeyang : What you both can help with are the remaining bugs. For example, there is one bug at the top of the basic.html test that has to do with relocating groups. I suspect the error is somewhere around lines 955-972.

**Comment by episodeyang** [comment]
I see I see, that makes a lot of sense. In terms of contributing I have a issue I wanted to solve for a long time, but haven't had time for yet. It is the diff granularity issue from last year. It might still be a while since I am trying to graduate and am desperately trying different things for my app trying to save it from oblivion, but I'm definitely coming back. Thanks again!

**Comment by johanneswilm** [comment]
@unbug I have added some logic so that marks those parts of the tree that it has diffed already as done. That gave me another speed boost of about a factor of 2.5-3 with your example. So it's now down at about 2-2.5 seconds from 27 seconds initially. It would be good if you could contribute by looking at the remaining bug in basic.html. You can also run random.html to see if you find any more bugs. Once we are reasonably sure that we have caught all bugs, this can be merged back into the mainline and a release be made.

**Comment by unbug** [comment]
@johanneswilm Just test it,amazing,it's really fast! Still 170kb html,10 times,4sec on my MBP.Good new is only 10sec on my iPhone6(iOS9 Safari),the page still gets stuck,but it's never crash again.I am look into the basic.html,it looks like fine here,when the diffcount is large then the cap,it throw a error,this happens in the old version,what else do I missing?

Also,we need a apply callback,in my case,after we apply the new html,we'll re-trigger the images lazy loading again.
```js
dd.apply(root,diffs,doneCallback);
```

**Comment by johanneswilm** [comment]
@unbug : Yes, the basic.html has a too high diffcount. But it is the same diff that is being created over and over again, so something with the application of that diff or the creation of it doesn't go the way it is supposed to. Almost all bugs are of that kind. So when I first started on fixing bugs yesterday, the random.html could on average handle about 2 cases and then create an error on the third. Then I fixed some 10 bugs, and now the numbers are much better. But I believe there are at least two bugs in there still. I included a failing case at the very top of the basic.html in the vdom branch.  

I would be OK with replacing the old version with the vdom branch, but first we need to have all the bugs gone -- at least all the bugs that show up regularly.

I am ok with adding callback functions. But let's do it consistently, so add them both to apply and diff. The diff function still takes much longer than the apply function (difference is about a factor of 1000 with large files).

As for further speed ups: I think I have taken most of the structural parts. But there may still be some advantage in fixing individual parts, replacing some functions with others that run quicker, and maybe by using a syntax such as nodeObj.nodeName instead of nodeObj[NODE_NAME]. I don't know how much that costs in terms of browser speed. The reason that was initially used was so that one could minimize the size of diffs sent over the network in production environments. But the code to do that could possibly best be placed somewhere else, such as in the part that converts DIffs to JSON.

@unbug: COuld you look at basic.html in the tests folder again and try to fix that bug? The console log should give you some initial information to work with.

**Comment by unbug** [comment]
@johanneswilm Just found a little bug,in line 144,missing to define the attribute
```js
      if (e1[ATTRIBUTES]) {
          var e1Attributes = Object.keys(e1[ATTRIBUTES]),
            e2Attributes = Object.keys(e2[ATTRIBUTES]),
            attribute;//define it

          if (e1Attributes.length != e2Attributes.length) {
              return false;
          }
          for (attribute in e1Attributes) {
              if (e1[ATTRIBUTES][attribute] !== e2[ATTRIBUTES][attribute]) {
                  return false;
              }
          }
      }
```

**Comment by johanneswilm** [comment]
@unbug thnx!

**Comment by unbug** [comment]
@johanneswilm no need to worry about the [bracket notation syntax any more](http://stackoverflow.com/a/30975165/479039)

**Comment by johanneswilm** [comment]
@unbug: Yes, but this is not just normal bracket annotation.

In the code it says `nodeObj[NODE_NAME]`. When using that, the computer first has to go see what `NODE_NAME` is equivalent to. If running in debug mode, `NODE_NAME` === "nodeName", so it will be `nodeObj["nodeName"]`. If running in production mode, `NODE_NAME` === 26, so it will be `nodeObj[26]`.

As I said, I don't know if this conversion from `NODE_NAME` to `26` before being able to assign the value has performance impacts. There may be other issues that are more critical.

**Comment by unbug** [comment]
@johanneswilm there is no need to clone the node again,because diffdom doesn't modify the node's attributes,also it's create all nodes by itself.

**Comment by johanneswilm** [comment]
@unbug What part of the code are you referring to?

**Comment by unbug** [comment]
@johanneswilm such as line 618
```js
            if (t1[NODE_NAME] !== t2[NODE_NAME]) {
                k = {};
                k[ACTION] = REPLACE_ELEMENT;
                k[OLD_VALUE] = cloneObj(t1); //nodeToObj(t1);
                k[NEW_VALUE] = cloneObj(t2); //nodeToObj(t2);
                k[ROUTE] = route;
                return [new Diff(k)];
            }
```

**Comment by unbug** [comment]
@johanneswilm I still can't find out what's the bug in basic.html,do you need me to do a real world use demo for in case?

**Comment by johanneswilm** [comment]
ehm, yes. I am unsure about that one. I've left it in for now in all the cases where it used to convert the DOM-node to a JS obj, which effectively cloned the node. I think in that case you may be right, but there may be other cases where it would make a difference. So I would prefer to do this step by step, and keep them all in until we have gotten rid of the bugs. We can then try to remove the cloning and see if that has any negative implications.

As for the bug in basic.html -- you do see the bug in the console, right?

It's when trying to diff these two divs with each other that the error appears:

``` 
<div class="32Z" data-test="2p" data-fisher="7gTAGB"><i><i data-id="yZm" class="W8nuT"><span class="R" data-test="6jFB"><b class="mHudJ"></b><b data-test="n9x">52K</b></span><b data-test="gBj" data-id="63vv"></b></i>J</i><i data-fisher="tNMbt" data-test="VhSee" class="yFJCis"><span data-id="jxc" data-fisher="mEBQ" class="As35"><i><p data-id="4m" data-test="V"><img></p><b data-test="ASKU" data-id="O3akk" class="p27s"></b>yYxD</i><b data-fisher="O" class="XjLs">w5</b>Z</span><img><span data-fisher="1H4z" data-test="Rzir"></span></i><img>I</div>
<div data-fisher="1NVn"><img><i><span data-fisher="lTtyKwl" class="Pf"><b data-id="i" data-test="C8h1" class="ucl"></b></span><b data-fisher="jFxhXH" data-test="RrZPMZ"><img>kwqvRK</b></i><b><span class="sAb3ap" data-fisher="wE"></span></b>WT</div>
```

I would start out by trying to remove individual parts of those divs until you have a minimal example that still shows the error. Then use the information that is in the console log to try to figure out what is going on, and going through the code.

**Comment by johanneswilm** [comment]
> also it's create all nodes by itself.

I don't know what you mean by that.

If we have the following two:

```
list1 = [{b:9},{c:10}];

list2 = [];

list2.push(list1[0]);

Then the first element of list1 is now in both, and if we change one of them, the other one will change as well, because we didn't clone it. So for example:

list2[0]['b'] = 34;

list1

# [{b:34},{c:10}]
```

It's to avoid this that I clone the node. It may not be needed in any of the cases, or it may be needed in some of the cases. But just to keep the amount of changes from the last working version to a minimum, I leave the cloning in until after the bug squashing.

**Comment by unbug** [comment]
@johanneswilm  diffdom can actually puts each objNode's parent obj when it create them,so we can access them everywhere,I am not sure what's this help by now,but if I do the levelsDeep again,that will help.
```js
 var nodeToObj = function(node,pObj) {
        var objNode = {};
        objNode[NODE_TYPE] = node.nodeType;
        objNode['PARENT_NODE'] = pObj;
        if (node.nodeType === 3 || node.nodeType === 8) {
            objNode[DATA] = node.data;
        } else {
            objNode[NODE_NAME] = node.nodeName;
            if (node.attributes && node.attributes.length > 0) {
                objNode[ATTRIBUTES] = {};
                Array.prototype.slice.call(node.attributes).forEach(
                    function(attribute) {
                        objNode[ATTRIBUTES][attribute.name] = attribute.value;
                    }
                );
            }
            if (node.childNodes && node.childNodes.length > 0) {
                objNode[CHILD_NODES] = [];
                Array.prototype.slice.call(node.childNodes).forEach(
                    function(childNode) {
                        objNode[CHILD_NODES].push(nodeToObj(childNode,objNode));
                    }
                );
            }
            if (node.value) {
                objNode[VALUE] = node.value;
            }
            if (node.checked) {
                objNode[CHECKED] = node.checked;
            }
            if (node.selected) {
                objNode[SELECTED] = node.selected;
            }
        }

        return objNode;
    };
```

**Comment by johanneswilm** [comment]
@unbug Hey, I don't think levelsDeep or the parent node help much right now. First we need those bugs gone, then we can think of new things. It would be like trying to paint the deck of a boat while it has a giant hole that lets water in at the bottom. First the repair, then the paint. :)

Worst case scenario is we find out the bugs cannot be controlled, or only be controlled in ways that make it slower than the original code, in which case we will have to throw this all out anyway.

Also, I don't think that was a good way to implement levels deep, if levels deep makes any sense. Instead we should simply have something that looks at the length of the current route array, not iterate over parent elements. And I'm not sure for how much else we can use that parent node. It will take up space in the types of diffs that contain portions of the nodeObj that will be sent around for no good reason.

**Comment by johanneswilm** [comment]
I was thinking we should probably get rid of nodeType as well, to keep things small, because nodeName already holds all the info needed to find the node type. And having it just makes the diffs larger than what they need to be. But this after the bugs have been squashed. :)

**Comment by unbug** [comment]
Hang on, I am still digging in the basic.html.
The parent node create a doubly linked list make sense,that shou help when diffdom apply the diffs.
I am reading the virtual-dom,node type is not much useful seens diffdom does not care about text node any more.

**Comment by johanneswilm** [comment]
> I am reading the virtual-dom,node type is not much useful seens diffdom does not care about text node any more.

No, that's not quite correct. Text nodes are still handled differently and they need to be, because when applying, some users will hook text merging mechanism in there.. But we can rely on simply using `nodeName==='#text'`instead. While tinkering with that, I found I could simplify the roughlyEqual, so I will push that now anyway.

Btw, I will close this PR, as this discussion no longer has much to to do with the original issue. Let's instead open a new issue just on vdom.

**Pull request closed without merging**
