### PR TITLE
Fixes #87 : trim white-spaces

### LINKED ISSUE #87: is there any way to handle or ignore white space ?
I'm getting more `diff` object due to white space.

codesandbox: https://codesandbox.io/s/1oqk7qpw64

image

### PR DESCRIPTION
**Pull request by ritwickdey**
First, thank you for the amazing library. :) 

I'm not sure this the good way to fix the issue but it's working :) #87

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey @ritwickdey - first of all: I am not opposed to adding an option to handle white space differently.

However, I am not entirely sure what all the parts you are proposing here do. It seems like with this option enabled, all text nodes lose all white space at the end and beginning, correct? So `<p>Hello <i>friend</i> of mine!</p>` turns into`<p>Hello<i>friend</i>of mine!</p>` which in plaintext is `Hellofriendof mine!`.

Is that correctly understood and is that really what you wanted to do?

Maybe something like this could work?:

```
data.trim().length ? data.replace(/^\s+|\s+$/g,' ') : ''
```

**Comment by ritwickdey** [comment]
Hi @johanneswilm, I'm talking about this white space. Please check the oldvalue and newValue
image

https://codesandbox.io/s/1oqk7qpw64

**Comment by ritwickdey** [comment]
I was trying to debug it. It's happening for next line + spacing (for indentation) .

**Comment by ritwickdey** [comment]
And yes. Naming conversion for `trimNodeTextValue` can be improved. I'm really bad for that. I agree :smile:

**Comment by johanneswilm** [comment]
@ritwickdey ues I understood the purpose of your patch. But my point is that it looks like it is removing both relevant and irrelevant space. If that is the case, it would be good if it could be changed to not delete relevant spaces.

**Comment by ritwickdey** [comment]
ok. I got your point. 

I applied the changes on '#text' node. Does '#text' node includes HTML p tag or any other HTMl Tag ?

I thought, it '#text' node means which node doesn't have any tag...

**Comment by ritwickdey** [comment]
e.g.

<div> 
text1
<p>text2</p>
</div>


I thought '#text' node will target only 'text1'. Is not it?

**Comment by johanneswilm** [comment]
#text nodes are all text nodes - inside or outside of other nodes. So basically all text.

**Comment by ritwickdey** [comment]
ok. Then you're right.. This PR has side-effects. 
Will update the PR

**Comment by johanneswilm** [comment]
This is relevant: https://medium.com/@patrickbrosset/when-does-white-space-matter-in-html-b90e8a7cdd33

The one thing we do not know is if a specific element is inline or block level because we don't know the css used for rendering.

**Comment by ritwickdey** [comment]
hmm.. interesting... May be in that case this patch is meaning less...

**Comment by johanneswilm** [comment]
No. I still think it makes sense. Under all circumstances the whitespace is turned into maximum one space. And doing that might cover your usecase as well with different amounts of indent.

**Comment by johanneswilm** [comment]
@ritwickdey Hey, I'm closing this PR now as it sounded like you were no longer interesting in merging it. Please reopen if I misunderstood.

**Pull request closed without merging**
