### PR TITLE
Distribute non-minified diffDOM.js

### LINKED ISSUE #121: Publish non-minified JS files on npm
Non-minified/beatified JS are defacto standard and are very handy for debugging.

I know there are `.map` files present, but they cannot be used all the time, not mentioning the JS files are sometimes needed to be edited for the actual debugging which is not possible now without fully rebuilding from TS.

This is a feature request to publish both non-minified JS files (`.js`) and minified (`.min.js`) on npm.

### PR DESCRIPTION
**Pull request by mvorisek**
like https://github.com/fiduswriter/diffDOM/commit/4f7443a5454d0b60582553449919edef6d0e4ec6, fix #121

### CODE REVIEW

**Comment by johanneswilm** [comment]
As mentioned earlier, the browser-verdion will not be metged. You need to fix your code on your side as described previously.

**Comment by mvorisek** [comment]
@johanneswilm this is not only ususal with jQuery, but really for almost every popular JS libs. Why you insist it so much? The non-minified version is not harmful, it is simply an another distributed format.

**Comment by johanneswilm** [comment]
I have explained previously and no new arguments have been made. You need to transpile yourself for your own end users as we cannot guarantee that our settings for transpiling targets match your end user browsers.
jQuery is a legacy app.

**Comment by mvorisek** [comment]
we use these JS libs - https://github.com/atk4/ui/blob/develop/public/external/package.json - all of them offer non-minified JS, and they are definitely not legacy

**Pull request closed without merging**
