### PR TITLE
Fix #128

### LINKED ISSUE #128: nodeToObj, stringToObj uppercase mishaps
This
https://github.com/fiduswriter/diffDOM/commit/1b3cfe7737ea62c93050658dea2217cef16eabb0
makes this comparison fails
https://github.com/fiduswriter/diffDOM/blob/24a11daa2d77df5885e019c086bfae514e43540c/src/diffDOM/virtual/diff.ts#L180C20-L180C20
when comparing a dom node to an html string.

### PR DESCRIPTION
**Pull request by GabrielLasso**
Fix #128

### CODE REVIEW

**Comment by johanneswilm** [comment]
How does that work inside of SVG where there actually is a difference
between upper- and lowercase tag names?

**Comment by GabrielLasso** [comment]
Hmm idk... But I am having an issue with `div` vs `DIV`

**Comment by icanfathom** [comment]
I'm having the same issue, mostly with div and DIV. `document.createElement('div')` creates a DIV, so when I pass in my string `<div></div>` to compare, it throws an error: Top level nodes have to be of the same kind.

**Comment by johanneswilm** [comment]
Has been fixed in version 5.1.0

**Pull request closed without merging**
